modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All rights reserved"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="${logo_file}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="citadel"
    mandatory=true
    versionRange="[1.12.7,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
